### ISSUE TITLE
install時のアーカイブダウンロードをリトライしたい

### ISSUE THREAD

**Issue by suwa-sh** [in-house-swagger/in-house-swagger#20]
### ストーリー
利用者 として
細い回線で利用を開始 するために、
install時のアーカイブダウンロードをresume/retry できる。

### 背景・経緯
細い回線でinstallを実行すると、容量の大きなアーカイブのダウンロードがエラー終了することがある。
途中までダウンロードした結果から、続きをダウンロードできるようにしたい。
中断しているので、正しくダウンロードできたか後で確認する仕組みも必要。

### 受け入れ条件
1. installがダウンロードでエラー終了した場合、リトライ できること
2. リトライでは、途中までダウンロードした結果の続きから再開 できること
3. md5 | sha1|asc(pgp) でダウンロード結果が壊れていないことを保証していること

### 対応詳細
1. bin/install local.gracefull_download に再開の考慮を追加 
2. bin/install local.download で再開オプションを追加
ファイルが存在する場合、curlに ```--continue-at``` オプションを付ける。
3. bin/install local.gracefull_download で md5 | sha1 | asc(pgp) の確認を追加
   基本は md5sum を想定(/tmpに.md5ファイルを作成し、md5sum -c でチェック)
   bintrayは asc とする。指定は bintray:プロジェクト名
4. config/project.propertiesにCHECKSUM_xxxを追加。定義なしはチェックしない。

**Comment by tkhr-sait** [comment]
ありがとうございます。対応詳細少し変更しました

**Comment by tkhr-sait** [comment]
timeout値を大きくさせてもらいました。検証はtimeoutを小さくすると手軽に検証できるかと。
と、ついでに _retcode / retcode の記載不良でエラー判定うまくいっていない部分も修正しました。

**Comment by suwa-sh** [comment]
良い感じですね！
一応、ちょこっとリファクタ掛けてみました。

1. local.download のcontinue判定をオプションに変更
1. \`cmd` は古いらしいので $(cmd) に置き換え
1. sedの正規表現がぱっと見で分からなかったので、bintray:projの分割部分は明示的なcutに変更
1. ログ出力を調整＋アーカイブ展開ログは LOGLEVEL_DEBUG の時だけに変更
