### ISSUE TITLE
バインドするホストを設定したい

### ISSUE THREAD

**Issue by suwa-sh** [in-house-swagger/in-house-swagger#21]
### ストーリー
利用者 として
他システムから接続 するために、
バインドするホストを設定 できる。

### 背景・経緯
複数IPを持っているマシン上で動かす場合など、明示的にバインドホストを指定したいことがありそう。

### 受け入れ条件
1. バインドするホストを設定 できること
1. spec-mgrにも同じホストが設定されること
1. デフォルトは設定なしで起動すること

### 対応詳細
1. bin/server start で jetty起動時にバインドホストの環境変数の付け外しを考慮
jetty.http.host
http://www.eclipse.org/jetty/documentation/9.4.x/configuring-connectors.html
1. デフォルトの起動ポートも合わせて 10000 に変更
1. spec-mgr にバインドホストの環境変数を引き継ぐ
server.address
https://stackoverflow.com/questions/23946369/how-to-configure-embedded-tomcat-integrated-with-spring-to-listen-requests-to-ip

### 課題
jettyの場合、jetty.http.host=指定なし だと、127.0.0.1, localhost, 自IP にアクセスできる
が
spring bootの場合、server.address=空文字 だと、127.0.0.1, localhostはOKだが、自IPはNG
application.ymlで server.addressの定義自体を付け外ししないといけないかも。。。

**Comment by tkhr-sait** [comment]
ちょっと検証してみました

jettyでも、
指定なし 0.0.0.0(=> * 全インターフェースでbind) /
空欄指定 127.0.0.1(spring bootと同じ動作)
現状、spring bootも指定なし 0.0.0.0 のようなので、
動作合わせられたらよさそうですね

> jetty起動引数を以下に変更して起動した場合(project.properties)
> JETTY_ARGS="jetty.http.host= jetty.http.port=${SERVER_PORT}"
> $ lsof -i tcp -P # 確認
> COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
> java    18018 sait   26u  IPv6 203652      0t0  TCP *:10001 (LISTEN)
> java    18643 sait  254u  IPv6 203691      0t0  TCP localhost:10000 (LISTEN)

> 指定なしの場合
> JETTY_ARGS="jetty.http.port=${SERVER_PORT}"
> $ lsof -i tcp -P
> COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
> java    19204 sait   26u  IPv6 207087      0t0  TCP *:10001 (LISTEN)
> java    19802 sait  254u  IPv6 204469      0t0  TCP *:10000 (LISTEN)

---
ちなみに、port 10000 は webmin で利用されているようなので、
10001,10002にしたほうがいいかもです。。。

**Comment by suwa-sh** [comment]
そうですね。

* 設定なし
    * jetty: 設定なし
    * spec-mgr: 設定なし
* 空文字指定（基本やりませんが）
    * jetty: 空文字
    * spec-mgr: 空文字
* 指定あり
    * jetty: 指定値
    * spec-mgr: 指定値

にしたいですねー

ただ
jettyは、起動引数を文字列で組み立てていて
spec-mgrは、application.yamlで環境変数を参照させていますf(^_^;
なので、application.yamlを動的に書き換えるか、環境変数を渡せるように考慮しないとダメかもですね。
今後の拡張などを考えると、環境変数を渡せるようにするのがベターかな。


ポートはまとめを見てみた感じだと 9700 とかが手頃ですかね。
複数台立てる時に、連番使いたいとかはあると思うので、きりの良いところでf(^_^;
https://ja.wikipedia.org/wiki/TCP%E3%82%84UDP%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E3%83%9D%E3%83%BC%E3%83%88%E7%95%AA%E5%8F%B7%E3%81%AE%E4%B8%80%E8%A6%A7

**Comment by tkhr-sait** [comment]
jettyと同じように、環境ファイルに定義されていたら、
サーバ起動時に -Dserver.address で指定できるくらいでよいのでは？
yamlより優先されるようですし...

ポート10001も使われてるんですね(^^;

**Comment by suwa-sh** [comment]
ポートは争奪戦ですねf(^_^;

in-house-swaggerからspec-mgr起動するところは、パラメータありですねー
ただ、現状のspec-mgrへの設定引き継ぎがちょっとややこしくて
「起動パラメータにするなら、ポートもパラメータに揃えないとな」ってくらいですー

* 経緯
spec-mgrは、gitでコンフリクトが発生したetcをコマンドラインで対応できるようにしているので
基本的に設定はprops持ち。webでも同じ動きをするように、yamlでpropsの環境変数を参照させている。
webでしか利用しない設定は、yamlのみで定義。


* AsIs
![before](https://user-images.githubusercontent.com/6545845/32705536-d68614ac-c858-11e7-9978-e1d01be00449.png)

* ToBe
![after](https://user-images.githubusercontent.com/6545845/32705762-be4fe99c-c85a-11e7-9f29-a84f87c77ef9.png)
    * spec-mgrのyaml
        * SERVER_HOST, SERVER_PORT はパラメータ、他はprops経由の環境変数
        * SERVER_PORT の環境変数を使っている部分は廃止 ※消しておかないと分かりにくそう。
        * 今後も、in-house-swagger -> spec-mgrの引き継ぎは、パラメータ指定に統一


な、感じでしょうか？

**Comment by suwa-sh** [comment]
不要そう、とのことで
一旦破棄しますー
