### ISSUE TITLE
デフォルトの起動ポートを設定したい

### ISSUE THREAD

**Issue by tkhr-sait** [in-house-swagger/in-house-swagger#24]
### ストーリー
利用者 として
起動時のトラブルを回避 するために、
デフォルトの起動ポート9700,9701で起動 できる。

### 背景・経緯
ポート8080,10000 等の場合、一般的な他サービスとポートが競合し、起動できない可能性がある。
ポートはまとめを見てみた感じだと 9700 とかが手頃ですかね。
複数台立てる時に、連番使いたいとかはあると思うので、きりの良いところでf(^_^;
https://ja.wikipedia.org/wiki/TCP%E3%82%84UDP%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E3%83%9D%E3%83%BC%E3%83%88%E7%95%AA%E5%8F%B7%E3%81%AE%E4%B8%80%E8%A6%A7

### 受け入れ条件
1. デフォルトポートは9700,9701で起動 できること
2. project.propertiesの設定で変更 できること

### 対応詳細
1. project.propertiesのSERVER_PORTを9700に変更

**Comment by tkhr-sait** [comment]
ホストはともかくポートはやっておきます。

**Comment by suwa-sh** [comment]
ありがとうございますー
